### ISSUE TITLE
Youtube Tutorial

### ISSUE THREAD

**Issue by XxAsSaSiNxX** [ShadowDog007/MobManager#25]
Please ShadowDog007 Im Not An Experienced Plugin Manager, and I Don't Manage This So Well, Would You Be Able To Make A Video Tutorial Of This Plugin Please It Would Be Amazing to Understand It For Me.

Thanks
XxAsSaSiNxX

**Comment by ShadowDog007** [comment]
Not an issue with code, and I don't do videos. Nor would I have time. Crii :'(
